
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        APdoctorDetails = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        APreceptionistDetails = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        APpatientDetails = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        APbedAvaliability = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        APlogOut = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        APpharmacistdetails = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        UpdateDocClose = new javax.swing.JButton();
        UpdateDocClose1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoadingscreenHM/Assets/doctor (2).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 140));

        APdoctorDetails.setBackground(new java.awt.Color(51, 153, 255));
        APdoctorDetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        APdoctorDetails.setText("Doctor Details");
        APdoctorDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APdoctorDetailsMouseClicked(evt);
            }
        });
        APdoctorDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APdoctorDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(APdoctorDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 190, 230));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoadingscreenHM/Assets/receptionist.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, -1));

        APreceptionistDetails.setBackground(new java.awt.Color(51, 153, 255));
        APreceptionistDetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        APreceptionistDetails.setText("Receptionist Details");
        APreceptionistDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APreceptionistDetailsMouseClicked(evt);
            }
        });
        jPanel3.add(APreceptionistDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 190, 230));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoadingscreenHM/Assets/examination.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        APpatientDetails.setBackground(new java.awt.Color(51, 153, 255));
        APpatientDetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        APpatientDetails.setText("Patient Details");
        APpatientDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APpatientDetailsMouseClicked(evt);
            }
        });
        jPanel4.add(APpatientDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 190, 230));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoadingscreenHM/Assets/hospital-bed (3).png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        APbedAvaliability.setBackground(new java.awt.Color(51, 153, 255));
        APbedAvaliability.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        APbedAvaliability.setText("Bed Avaliability");
        APbedAvaliability.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APbedAvaliabilityMouseClicked(evt);
            }
        });
        APbedAvaliability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APbedAvaliabilityActionPerformed(evt);
            }
        });
        jPanel5.add(APbedAvaliability, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 190, 230));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Admin Panel");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        APlogOut.setBackground(new java.awt.Color(242, 38, 19));
        APlogOut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        APlogOut.setForeground(new java.awt.Color(255, 255, 255));
        APlogOut.setText("Log Out");
        APlogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APlogOutActionPerformed(evt);
            }
        });
        jPanel1.add(APlogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 130, 50));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        APpharmacistdetails.setBackground(new java.awt.Color(51, 153, 255));
        APpharmacistdetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        APpharmacistdetails.setText("Pharmacist Details");
        APpharmacistdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APpharmacistdetailsActionPerformed(evt);
            }
        });
        jPanel6.add(APpharmacistdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoadingscreenHM/Assets/pharmacist.png"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 130));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 190, 230));

        UpdateDocClose.setBackground(new java.awt.Color(255, 0, 51));
        UpdateDocClose.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateDocClose.setForeground(new java.awt.Color(255, 255, 255));
        UpdateDocClose.setText("X");
        UpdateDocClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UpdateDocClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDocCloseActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateDocClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 50, 25));

        UpdateDocClose1.setBackground(new java.awt.Color(44, 62, 80));
        UpdateDocClose1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UpdateDocClose1.setForeground(new java.awt.Color(255, 255, 255));
        UpdateDocClose1.setText("-");
        UpdateDocClose1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UpdateDocClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDocClose1ActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateDocClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 50, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoadingscreenHM/Assets/HSAdmin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void APdoctorDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APdoctorDetailsMouseClicked
       new AdminDoctor().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_APdoctorDetailsMouseClicked

    private void APreceptionistDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APreceptionistDetailsMouseClicked
       AdminReceptionist ADRecp = new AdminReceptionist();
       ADRecp.setVisible(true);
       ADRecp.pack();
       ADRecp.setLocationRelativeTo(null);
       ADRecp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_APreceptionistDetailsMouseClicked

    private void APpatientDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APpatientDetailsMouseClicked
       AdminPatient ADPat = new AdminPatient();
       ADPat.setVisible(true);
       ADPat.pack();
       ADPat.setLocationRelativeTo(null);
       ADPat.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_APpatientDetailsMouseClicked

    private void APbedAvaliabilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APbedAvaliabilityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_APbedAvaliabilityMouseClicked

    private void APlogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APlogOutActionPerformed
       
       int check = JOptionPane.showConfirmDialog(null,"DO YOU WANT TO LOG OUT ?");
       if (check == 0){
       LoginAs12 logas = new LoginAs12();
       logas.setVisible(true);
       logas.pack();
       logas.setLocationRelativeTo(null);
       logas.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose(); 
       }
    }//GEN-LAST:event_APlogOutActionPerformed

    private void APdoctorDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APdoctorDetailsActionPerformed
        
    }//GEN-LAST:event_APdoctorDetailsActionPerformed

    private void APbedAvaliabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APbedAvaliabilityActionPerformed
       ADBed ADB = new ADBed();
       ADB.setVisible(true);
       ADB.pack();
       ADB.setLocationRelativeTo(null);
       ADB.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_APbedAvaliabilityActionPerformed

    private void APpharmacistdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APpharmacistdetailsActionPerformed
       AdminPharmacy1 ADP = new AdminPharmacy1();
       ADP.setVisible(true);
       ADP.pack();
       ADP.setLocationRelativeTo(null);
       ADP.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_APpharmacistdetailsActionPerformed

    private void UpdateDocCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDocCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_UpdateDocCloseActionPerformed

    private void UpdateDocClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDocClose1ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_UpdateDocClose1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton APbedAvaliability;
    private javax.swing.JButton APdoctorDetails;
    private javax.swing.JButton APlogOut;
    private javax.swing.JButton APpatientDetails;
    private javax.swing.JButton APpharmacistdetails;
    private javax.swing.JButton APreceptionistDetails;
    private javax.swing.JButton UpdateDocClose;
    private javax.swing.JButton UpdateDocClose1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
