
import hospitalsystem.DBConnect;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class LoginDoctor extends javax.swing.JFrame {

    PreparedStatement pst = null;
    CreateStatement cs = null;
    ResultSet rs = null;
    
    public LoginDoctor() {
        initComponents();
        this.setLocationRelativeTo(null);
        Connection con = DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DLMin = new javax.swing.JLabel();
        DLClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DLpasswordBox = new javax.swing.JPasswordField();
        DLunamebox = new javax.swing.JTextField();
        DLogin = new javax.swing.JButton();
        Dcancel = new javax.swing.JButton();
        ADPatBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hospital Management System");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        DLMin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DLMin.setText("-");
        DLMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DLMinMouseClicked(evt);
            }
        });
        jPanel1.add(DLMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 20, -1));

        DLClose.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DLClose.setText("X");
        DLClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DLClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DLCloseMouseClicked(evt);
            }
        });
        jPanel1.add(DLClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(978, -3, 20, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hospital Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Doctor Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 260, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("User Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, 23));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Password   :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        DLpasswordBox.setBackground(new java.awt.Color(108, 122, 137));
        DLpasswordBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DLpasswordBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(DLpasswordBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 260, 40));

        DLunamebox.setBackground(new java.awt.Color(108, 122, 137));
        DLunamebox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DLunamebox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(DLunamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 260, 40));

        DLogin.setBackground(new java.awt.Color(34, 167, 240));
        DLogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DLogin.setForeground(new java.awt.Color(255, 255, 255));
        DLogin.setText("LOGIN");
        DLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DLoginActionPerformed(evt);
            }
        });
        jPanel1.add(DLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, -1, 50));

        Dcancel.setBackground(new java.awt.Color(242, 38, 19));
        Dcancel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Dcancel.setForeground(new java.awt.Color(255, 255, 255));
        Dcancel.setText("CANCEL");
        Dcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DcancelActionPerformed(evt);
            }
        });
        jPanel1.add(Dcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 150, 50));

        ADPatBack.setBackground(new java.awt.Color(255, 255, 255));
        ADPatBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ADPatBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoadingscreenHM/Assets/previous (1).png"))); // NOI18N
        ADPatBack.setText("Back");
        ADPatBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ADPatBack.setBorderPainted(false);
        ADPatBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADPatBackActionPerformed(evt);
            }
        });
        jPanel1.add(ADPatBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginNewww.png"))); // NOI18N
        jLabel8.setText("jLabel1");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoadingscreenHM/Assets/loginNewww.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DLMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLMinMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_DLMinMouseClicked

    private void DLCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_DLCloseMouseClicked

    private void DLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DLoginActionPerformed
        /*DoctorPanel DP = new DoctorPanel();
        DP.setVisible(true);
        DP.pack();
        DP.setLocationRelativeTo(null);
        DP.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
        String username = DLunamebox.getText();
        String password = DLpasswordBox.getText();
        
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/hospitalmanagementsystem","root","");
            String sql = "SELECT * FROM admin_doctor WHERE duname= ? and dpass= ?";
            pst = con.prepareStatement(sql);
            pst.setString(1,username);
            pst.setString(2,password);
            
            rs = pst.executeQuery();
            if (rs.next()){
                String userid = rs.getString("did");
                this.setVisible(false);
                new DoctorPanel(userid).setVisible(true);
            }else{
             JOptionPane.showMessageDialog(this, "User Name or Password is Incorrect");
             DLunamebox.setText("");
             DLpasswordBox.setText("");
            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null , e);
        }
    }//GEN-LAST:event_DLoginActionPerformed

    private void DcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DcancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_DcancelActionPerformed

    private void ADPatBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADPatBackActionPerformed
        LoginAs12 LA = new LoginAs12();
        LA.setVisible(true);
        LA.pack();
        LA.setLocationRelativeTo(null);
        LA.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ADPatBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADPatBack;
    private javax.swing.JLabel DLClose;
    private javax.swing.JLabel DLMin;
    private javax.swing.JButton DLogin;
    private javax.swing.JPasswordField DLpasswordBox;
    private javax.swing.JTextField DLunamebox;
    private javax.swing.JButton Dcancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
